// Code generated by Slice Machine. DO NOT EDIT.

import dynamic from 'next/dynamic';

export const components = {
  banner: dynamic(() => import('./Banner')),
  banner_with_calendar: dynamic(() => import('./BannerWithCalendar')),
  banner_with_text: dynamic(() => import('./BannerWithText')),
  billing_form: dynamic(() => import('./BillingForm')),
  block_text_centered: dynamic(() => import('./BlockTextCentered')),
  click_and_collect_grid: dynamic(() => import('./ClickAndCollectGrid')),
  customer_logos: dynamic(() => import('./CustomerLogos')),
  divider: dynamic(() => import('./Divider')),
  form: dynamic(() => import('./Form')),
  image_card_with_cta: dynamic(() => import('./ImageCardWithCta')),
  image_grid: dynamic(() => import('./ImageGrid')),
  image_left_and_text_grid: dynamic(() => import('./ImageAndTextGrid')),
  image_slider: dynamic(() => import('./ImageSlider')),
  image_text_and_cta_grid_left: dynamic(() => import('./ImageTextAndCtaGridLeft')),
  job_offers: dynamic(() => import('./JobOffers')),
  job_sidebar: dynamic(() => import('./JobSidebar')),
  page_title_underlined: dynamic(() => import('./PageTitleUnderlined')),
  text_and_stepper: dynamic(() => import('./TextAndStepper')),
  timeline: dynamic(() => import('./Timeline')),
  video_and_text_grid: dynamic(() => import('./VideoAndTextGrid')),
};
